### ISSUE TITLE
fix: overlapping textarea

### ISSUE THREAD

**Issue by hammadsaedi** [hammadsaedi/regex-pro#1]
Textarea is used in form.
![image](https://github.com/hammadsaedi/regex-pro/assets/71373419/feaaeeec-b3d4-468c-ad70-12775ae88ffc)

It is not bound to form an element. 
![image](https://github.com/hammadsaedi/regex-pro/assets/71373419/bb04d310-51ff-4de5-b183-5963677913fe)

update `style.css`

**Comment by hammadsaedi** [comment]
consider this condition as well :)
![image](https://github.com/hammadsaedi/regex-pro/assets/71373419/87c99a5e-70ab-43d8-b449-1996a3e04c06)

**Comment by muhammadammar33** [comment]
bhai yeh bhi mujhy dy do

**Comment by hammadsaedi** [comment]
project hi apka hy :)

**Comment by hammadsaedi** [comment]
fixed by https://github.com/hammadsaedi/regex-pro/pull/17
