### ISSUE TITLE
Broken Link in Demo Section of README

### ISSUE THREAD

**Issue by hammadsaedi** [hammadsaedi/regex-pro#13]
## Description
The link in the "Demo" section of the `README.md` is broken and needs to be fixed.

## Location
- File: `README.md`
- Section: "Demo"

## Expected Corrected Link
[hammadsaedi.github.io/regex-pro/](https://hammadsaedi.github.io/regex-pro/)

## Steps to Reproduce

1. Open the repository's `README.md` file.
2. Scroll down to the "Demo" section.
3. Locate the link that is supposed to lead to the demo website.
4. Click on the link.

## How to Fix

You can fix the broken link directly from the GitHub web interface without the need to clone the repository locally. Follow these steps:

1. **Fork the Repository**: If you haven't already, fork the repository to create your own copy. You can do this by clicking the "Fork" button at the top right of the repository's page.

2. **Edit `README.md` on GitHub**:
   - Navigate to your fork of the repository on GitHub.
   - Open the `README.md` file by clicking on it.

3. **Locate the Broken Link**: Scroll down to the "Demo" section of the `README.md` file and locate the broken link.

4. **Edit the `README.md` File**:
   - Click the "Edit" (pencil) button in the top right corner of the `README.md` file to open the online Markdown editor.
   - Replace the broken link with the correct one.
   - Ensure the link is properly formatted with the correct URL.

5. **Preview Your Changes**: Most online Markdown editors on GitHub provide a preview option. Verify that the link displays correctly.

6. **Commit Changes**: Scroll down to the bottom of the page. In the "Commit changes" section:
   - Provide a commit title describing your change, e.g., "Fix broken link in 'Demo' section of README."
   - Optionally, provide a brief description of the change.
   - Make sure the "Create a new branch for this commit and start a pull request" option is selected.

7. **Create a Pull Request (PR)**:
   - After committing your changes, GitHub will prompt you to create a pull request.
   - Review your changes and add any additional comments if needed.
   - Click the "Create pull request" button.

8. **Collaborate and Test**: Be prepared to collaborate with maintainers and make any necessary changes based on their feedback.

By following these steps, you can contribute to fixing the broken link directly from the GitHub web interface without the need to clone the repository locally. This approach is convenient for quick fixes.

**Comment by harshvyas-22** [comment]
Fix broken link in 'Demo' section of README closes #13
