### ISSUE TITLE
Implement IP address extraction functionality using regular expressions

### ISSUE THREAD

**Issue by hammadsaedi** [hammadsaedi/regex-pro#16]
## Issue Description

In many web applications, there is a common requirement to extract IP addresses from text. This issue is to add IP address extraction functionality to our Regex Pro project, which allows users to work with regular expressions.

## Task

Your task is to implement IP address extraction using regular expressions. Here are the requirements for this task:

1. Implement the regular expression pattern to extract IP addresses from the input text.
2. Add the regular expression pattern in the `extractionForms` in `pages.js`.

## Additional Information

- You can refer to the existing extraction forms as examples.
- The regular expression pattern for IP address extraction should cover common IPv4 and, if needed, IPv6 address formats.
- You may find resources online to help with regular expressions for IP address extraction.

## Getting Started

1. Fork this repository to your GitHub account.
2. Create a new branch for this task.
3. Implement the changes as described.
4. Commit your changes and push them to your fork.
5. Open a pull request to this repository.

## Additional Notes

- This is a "Good First Issue" suitable for contributors who are new to the project and want to get involved.
- Please reach out if you have any questions or need assistance with the task.

We look forward to your contribution! 😄

**Comment by HasaanAhmad** [comment]
Assign me this issue. I will look into it.

**Comment by hammadsaedi** [comment]
Best of Luck 👍

**Comment by hammadsaedi** [comment]
Fixed by PR https://github.com/hammadsaedi/regex-pro/pull/18
