### ISSUE TITLE
Implement Password Validation for Regex Pro

### ISSUE THREAD

**Issue by hammadsaedi** [hammadsaedi/regex-pro#19]
# Password Validation for Regex Pro

## Background
Password validation is a critical aspect of web application security. We want to enhance the Regex Pro project by implementing password validation using regular expressions.

## Task
Your task is to implement password validation using regular expressions. Here are the requirements for this task:

1. Design a regular expression pattern for password validation that adheres to security best practices.
2. Add the regular expression in the `validationForms` in `pages.js`.

## Getting Started:
1. Fork this repository to your GitHub account.
2. Create a new branch for this task.
3. Implement the changes as described.
4. Commit your changes and push them to your fork.
5. Open a pull request to this repository.

## Password Validation Requirements
- The password should be at least 8 characters long.
- It should include at least one uppercase letter.
- It should include at least one lowercase letter.
- It should include at least one numeric digit.
- It should include at least one special character (e.g., !, @, #, $, etc.).

## Additional Notes
- This is a "Good First Issue" suitable for contributors who are new to the project and want to get involved.
- Please reach out if you have any questions or need assistance with the task.

We look forward to your contribution! 😄

**Comment by ndbn17** [comment]
Hi, can I try to solve this issue please?

**Comment by hammadsaedi** [comment]
Yeah, of course.
