### ISSUE TITLE
fix: responsive header

### ISSUE THREAD

**Issue by hammadsaedi** [hammadsaedi/regex-pro#2]
the header is not responsive.
![image](https://github.com/hammadsaedi/regex-pro/assets/71373419/df3fc273-1a73-40b7-8cdd-27342687356e)

make the side navigation menu with a good CSS.

**Comment by muhammadammar33** [comment]
Bhai yeh bhi merey ko dy do

**Comment by hammadsaedi** [comment]
Best of luck :)

**Comment by hammadsaedi** [comment]
@muhammadammar33 make sure to link your PR with this issue 👍

**Comment by HaroonKhalid222** [comment]
🙂

**Comment by hammadsaedi** [comment]
@HaroonKhalid222 you can see other issues 👀
