### ISSUE TITLE
Implement Phone Number Validation

### ISSUE THREAD

**Issue by hammadsaedi** [hammadsaedi/regex-pro#4]
### Background
Phone number validation is a common requirement in various web applications. We want to add phone number validation to our Regex Pro project, which allows users to test and work with regular expressions for validation.

### Task
Your task is to implement phone number validation using regular expressions. Here are the requirements for this task:
- Design the regular expression pattern for phone number validation.
- Add regular expression in validationForms in `pages.js`

### Getting Started:

- Fork this repository to your GitHub account.
- Create a new branch for this task.
- Implement the changes as described.
- Commit your changes and push them to your fork.
- Open a pull request to this repository.

### Additional Notes

This is a "Good First Issue" suitable for contributors who are new to the project and want to get involved.
Please reach out if you have any questions or need assistance with the task.

We look forward to your contribution! 😄

**Comment by JavTahir** [comment]
i want to work on this issue . can you assign me this ?

**Comment by JavTahir** [comment]
Phone numbers are of different pattern globally. do i have to do it for all or for specific one :..(

**Comment by hammadsaedi** [comment]
yes, of course :)

**Comment by JavTahir** [comment]
making a one regex exp is complex for all phone numbers.
can there be two?

**Comment by hammadsaedi** [comment]
This should work out:
`^(\+\d{1,2}\s?)?1?\-?\.?\s?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}$`

**Comment by hammadsaedi** [comment]
fixed https://github.com/hammadsaedi/regex-pro/pull/35
