### ISSUE TITLE
Implement Phone Number Extraction

### ISSUE THREAD

**Issue by hammadsaedi** [hammadsaedi/regex-pro#6]
### Background
In many web applications, extracting phone numbers from text is a common requirement. We want to add phone number extraction functionality to our Regex Pro project, which allows users to work with regular expressions.

### Task
Your task is to implement phone number extraction using regular expressions. Here are the requirements for this task:

Implement the regular expression pattern to extract phone numbers from the input text.
Add regular expression in extractionForms in `pages.js`

### Additional Information

You can refer to the existing extraction forms as examples.
The regular expression pattern for phone number extraction should cover common phone number formats.
You may find resources online to help with regular expressions for phone number extraction.

### Getting Started

Fork this repository to your GitHub account.
Create a new branch for this task.
Implement the changes as described.
Commit your changes and push them to your fork.
Open a pull request to this repository.

### Additional Notes

This is a "Good First Issue" suitable for contributors who are new to the project and want to get involved.
Please reach out if you have any questions or need assistance with the task.

We look forward to your contribution! 😄

**Comment by NUMS-half** [comment]
Hi, could you please assign this issue to me?

**Comment by hammadsaedi** [comment]
plz comment on issue

**Comment by bryce-seefieldt** [comment]
Can I give this a try?

**Comment by hammadsaedi** [comment]
Yes, go ahead

**Comment by bryce-seefieldt** [comment]
Updates to [PR32](https://github.com/hammadsaedi/regex-pro/pull/32) made via new commit [c4c41bb](https://github.com/hammadsaedi/regex-pro/pull/32/commits/c4c41bbf63b31e18ea9e335d40a5f7215fb42afb). 
Please let me know if this works for you.
