### ISSUE TITLE
Implement SQL Code Removal from Text

### ISSUE THREAD

**Issue by hammadsaedi** [hammadsaedi/regex-pro#7]
### Background
For security and data integrity, it's important to prevent SQL injection in web applications. To enhance our project, Regex Pro, we need to implement a feature that can detect and remove SQL code from text, helping to safeguard the application against malicious input.

### Task
Your task is to implement SQL code detection and removal from text. Here are the requirements for this task:
- Implement regular expression pattern for SQL code
- Add regular expression in sanitizationForm in `pages.js`

### Additional Information:

- You can refer to the existing sanitization forms as examples.
- SQL code can take various forms, including statements, comments, and common keywords (e.g., SELECT, DROP, UNION).
- You may find resources and regular expressions online to help with SQL code detection and removal.

### Getting Started:

- Fork this repository to your GitHub account.
- Create a new branch for this task.
- Implement the changes as described.
- Commit your changes and push them to your fork.
- Open a pull request to this repository.

### Additional Notes:

This is a "Good First Issue" suitable for contributors who are new to the project and want to get involved.
Please reach out if you have any questions or need assistance with the task.

We look forward to your contribution! 😄

**Comment by sfazli96** [comment]
Hi! I am new to this project and a new contributor. I have a question about the SQL code. So this issue is to create an SQL removal from text meaning that when the text shows it removes it? This is where I am a little confused. Can you explain a bit more? I want to give this issue a try. Thank you!

**Comment by hammadsaedi** [comment]
Yes, We want to remove SQL code from text. Please explore web: https://hammadsaedi.github.io/regex-pro/

We have HTML remover:
![image](https://github.com/hammadsaedi/regex-pro/assets/71373419/9d1e0d05-5b15-4c8d-a4ab-e6780f7ab5f9)

The project uses Regular Expressions. Basically, you used to come up with regular expressions to detect SQL code. 

:)

**Comment by sfazli96** [comment]
Just wanted to update that I created a pull request, I added in the form but the other part similar to the remove HTML part is where I want a bit more clarification in where that is happening. Thank you!
