### ISSUE TITLE
Implement the regular expression pattern for Date Extraction

### ISSUE THREAD

**Issue by hammadsaedi** [hammadsaedi/regex-pro#8]
**Background**:
In various applications, extracting dates from text is a common requirement. We want to add date extraction functionality to our Regex Pro project, which allows users to work with regular expressions.

**Task**:
Your task is to implement the regular expression pattern for date extraction. Here are the requirements for this task:
1. Implement the regular expression pattern to extract dates from the input text.
2. Add in extractionForms in `pages.js`

**Additional Information**:
- You can refer to the existing extraction forms as examples.
- The regular expression pattern for date extraction should cover various date formats (e.g., MM/DD/YYYY, YYYY-MM-DD, and more).

**Getting Started**:
1. Fork this repository to your GitHub account.
2. Create a new branch for this task.
3. Implement the changes as described.
4. Commit your changes and push them to your fork.
5. Open a pull request to this repository.

**Additional Notes**:
- This is a "Good First Issue" suitable for contributors who are new to the project and want to get involved.
- Please reach out if you have any questions or need assistance with the task.

We look forward to your contribution! 😄

**Comment by muhammadsaadgondal** [comment]
assign me

**Comment by hammadsaedi** [comment]
@saadjutt10 you should work on issue 1 - 3 :)

**Comment by muhammadsaadgondal** [comment]
I wish i could, but i don't want to :)
