### ISSUE TITLE
Implement the regular expression pattern for URL Extraction

### ISSUE THREAD

**Issue by hammadsaedi** [hammadsaedi/regex-pro#9]
**Background**:
URL extraction is a common requirement in various applications. We want to add URL extraction functionality to our Regex Pro project, allowing users to easily extract URLs from text using regular expressions.

**Task**:
Your task is to implement the regular expression pattern for URL extraction. Here are the requirements for this task:
3. Implement the regular expression pattern to extract dates from the input text.
4. Add in extractionForms in `pages.js`

**Additional Information**:
- You can refer to the existing extraction forms as examples.
- The regular expression pattern for URL extraction should cover common URL formats (e.g., http://example.com, https://www.example.com).

**Getting Started**:
1. Fork this repository to your GitHub account.
2. Create a new branch for this task.
3. Implement the changes as described.
4. Commit your changes and push them to your fork.
5. Open a pull request to this repository.

**Additional Notes**:
- This is a "Good First Issue" suitable for contributors who are new to the project and want to get involved.
- Please reach out if you have any questions or need assistance with the task.

We look forward to your contribution! 😄

**Comment by fasiiha** [comment]
okay

**Comment by hammadsaedi** [comment]
Not okay 🙂

**Comment by hammadsaedi** [comment]
Resolved https://github.com/hammadsaedi/regex-pro/pull/11
